@baseUrl = localhost:3000


### Send test GET method
GET http://{{baseUrl}}/apis

### Send test POST method
POST http://{{baseUrl}}/apis/test/abc?options[page]=1&options[limit]=6&options[sort][metadata.latestReviewAt]=desc&options[sort][info.searchCount]=desc&options[sort][createdAt]=desc&populate[0]=__headquarters&populate[1]=__logoMedia HTTP/1.1
content-type: application/json

{
    "data": {
        "age": "234",
        "name": "sample",
        "time": "Wed, 21 Oct 2015 18:27:50 GMT"
    }
}

### Send test PUT method
PUT http://{{baseUrl}}/test
Content-Type: "application/json"

### Send test PATCH method
PATCH http://{{baseUrl}}/test/abc/23
Content-Type: "application/json"

### Send test DELETE method
DELETE http://{{baseUrl}}/test

### Send test OPTIONS method
OPTIONS http://{{baseUrl}}/test
